title: Shovel-Headed Kill Machine
author: kiehozero
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
A blog all about mid-tempo Exodus riffs.
theme: minima

# social links
twitter_username: topes_lose # DO NOT include the @ character, or else the build will fail!
github_username:  kiehozero # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
